version: "3"
services:
  nodejs-notes-app:
    container_name: nodejs-notes-app
    build:
      context: ./
      dockerfile: Dockerfile
    image: nodejs-notes-app
    restart: always
    network_mode: bridge
    env_file: .env
    ports:
      - "11011:11011"
